from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier
from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.mollisen_hand_classifier.mollisen_left_hand_classifier import MollsenLeftHandClassifier
from model.mollisen_hand_classifier.mollisen_right_hand_classifier import MollsenRightHandClassifier
from model.mollisen_hand_classifier.mollisen_2hands_classifier import Mollsen2HandsClassifier
from model.keypoint_android_classifier.keypoint_android_classifier import KeyPointAndroidClassifier
from model.keypoint_android_classifier.keypoint_android_2hands_classifier import KeyPointAndroid2handsClassifier